### ISSUE TITLE
`sensivitityTimeProfiles` and `sensitivitySpiderPlot` should save to png

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#160]
Instead of using `savePlotList`

**Comment by IndrajeetPatil** [comment]
What about filenames for these plots? Should the user specify them, or should we have some defaults?

If there are multiple output paths, there will be multiple plots (one for each path), and so users will need to specify a vector of filename paths, which, I feel, is a lot of work. 

I would vote for us naming these files internally with some sensible naming pattern, like `Profile_OutputPath1.png`, `Profile_OutputPath2.png`, etc. The prefix `Profile_` is needed because there will also be spider plots, and they will also have similar naming schema:  `Spider_OutputPath1.png`, `Spider_OutputPath2.png`, etc. 

If we don't want to use prefix, another option is to create and write to separate folders for each type of plot:  
`Profile Plots/OutputPath1.png`, `Profile Plots/OutputPath2.png`, ...
`Spider Plots/OutputPath1.png`, `Spider Plots/OutputPath2.png`, ...

**Comment by PavelBal** [comment]
Yes agree, Profile_OuputPath1 etc is good.

Indrajeet Patil ***@***.***> schrieb am Di., 15. Feb. 2022,
09:43:
