### ISSUE TITLE
`sensitivityTimeProfiles` color palette

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#228]
![image](https://user-images.githubusercontent.com/25903040/168297210-e0f1c9fc-f89b-4812-92e3-4a629797eb4f.png)

The current pallete is too pale, I am having hard times focusing on the lines. I would like to try out the esqlabs-palette.

**Comment by msevestre** [comment]
Agreed

**Comment by IndrajeetPatil** [comment]
> I would like to try out the esqlabs-palette.

I already tried this and explained why this won't work [here](https://github.com/esqLABS/esqlabsR/issues/162#issuecomment-1092926586).

> The current pallete is too pale

I think this might be due to #227. Can you reassess this issue once #235 has been merged? I've a hunch that's going to improve things. 

If you still want a different palette, available palettes can be seen here: https://github.com/esqLABS/esqlabsR/issues/162#issuecomment-1046577893

**Comment by IndrajeetPatil** [comment]
Is this still relevant?

![image](https://user-images.githubusercontent.com/11330453/179967950-cb84a767-4e19-4922-8ad6-8d2549b52b1b.png)

**Comment by PavelBal** [comment]
Yes let's keep it for now and get some feedback from other users. Low prio though.
