### ISSUE TITLE
Change outputFolder for plots

### ISSUE THREAD

**Issue by VanessaBa** [esqLABS/esqlabsR#495]
Currently all generated plots are directly saved in the outputFolder of the ProjectConfiguration (by default: 'Results'). This is not optimal since the plots are replaced when they are re-generated. 

It would be useful if 
1) the default folder is the same folder where the results (csv & pkml files) go or are loaded from (my main issue)
2) the folder is customizable , i.e., something like a `outputFolderPlots` (optional)

**Comment by PavelBal** [comment]
- `createPlotsFromExcel` gets a new argument `outputFolder`. If provided, the plots are saved in the specified folder. If `NULL`, default results folder as defined in the `ProjectConfiguration` is used.

- Function `saveScenarioResults` returns the path where the results were saved.

- Function `createEsqlabsExportConfiguration` requires a new argument `outputFolder` instead of `projectConfiguration`.


The workflow to save the plots in the same folder as the results is presented in the example project:

https://github.com/esqLABS/esqlabsR/blob/00558d53bff06d0cf4973c5867f6a913f7f1a86c/inst/extdata/examples/TestProject/Code/Scenarios/defaultScenario.R#L46

and https://github.com/esqLABS/esqlabsR/blob/00558d53bff06d0cf4973c5867f6a913f7f1a86c/inst/extdata/examples/TestProject/Code/Scenarios/defaultScenario.R#L72-L78

**Comment by PavelBal** [comment]
@VanessaBa Hope this is an acceptable solution
