### ISSUE TITLE
`PlotsFileEditor` - better file selection dialog?

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#526]

**Comment by Felixmil** [comment]
The advantage of the currently used `file.choose()` is that it returns a path to local computer. Which is necessary since the application is supposed to read other local files based on the `ProjectConfiguration.xlsx` file.

The default and better looking `shiny::fileInput()` will actually **upload** the selected file to a temporary directory (but of course, not all `Parameters/` files. Si when paths specified in `ProjectConfiguration.xlsx` are read, it cannot find the `Parameters/` files and other resources.

The alternative would be to allow the user to **paste** its file path in a `shiny::textInput()` field. 

Another way would be to use (`{shinyFiles}`)[https://github.com/thomasp85/shinyFiles] wich access files without copying them to a temporary location.

> This package extends the functionality of shiny by providing an API for client side access to the server file system. As many shiny apps are run locally this is equivalent to accessing the filesystem of the users own computer, without the overhead of copying files to temporary locations that is tied to the use of fileInput().

Run this and browse to an excel project file to test it:
```r
library(shiny)
library(shinyFiles)

# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
  titlePanel("{shinyFiles} test"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(shinyFilesButton('files', label='File select', title='Please select a file', multiple=FALSE)),
    
    # Show a plot of the generated distribution
    mainPanel(
      verbatimTextOutput("path")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  volumes <- c(home = "~", root='.')
  
  shinyFileChoose(input, 'files', root=volumes, filetypes=c('xlsx'))
  
  # when input$files changes render it as printed text. If input$files is integer,
  # then return a text saying that no file were selected
  output$path <- renderPrint({
    if(is.integer(input$files)) {
      return("No file selected yet")
    }
    parseFilePaths(volumes, input$files)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)

```
