### ISSUE TITLE
Check the "scripts" folder

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#91]
Check which scripts are required and which are not.

**Comment by IndrajeetPatil** [comment]
@msevestre Since I did not want to create two copies of the [scripts](https://github.com/esqLABS/esqlabsR/tree/develop/scripts) folder (these scripts are the same as in OSP repositories), so I created a [fork](https://github.com/esqLABS/build-scripts) and tried including scripts as a git submodule (just like in OSP):

https://github.com/esqLABS/esqlabsR/blob/6700ffce1882d5bb054193fe450ee3d816e2d190/.gitmodules#L1-L3

But, if I do this, AppVeyor doesn't work because it can't find the `scripts` folder. Is there no workaround to not duplicate `scripts` folder in this repository?

**Comment by msevestre** [comment]
@IndrajeetPatil Why are you forking the scripts repo and not using the one from OSP directly? Using submodules effectively references a specific commit and there is no need of breaking compatibility as long as you do not update. I would suggest 

1. deleting the scripts folder in the code
2. Referencing OSP build scripts and not esqLABS
3. In your appveyor, this line is missing
4. https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/develop/appveyor.yml#L12

This is also something that needs to be run locally to get the submodules

I have created in my gitprofile the following alias

`	su = !git submodule update --init --recursive`

so I only call `git su` when I clone a repo

**Comment by msevestre** [comment]
Correction. The line is here. So simply delete your script folder

**Comment by msevestre** [comment]
it will then look like so
![image](https://user-images.githubusercontent.com/1041237/136032434-5e55380d-9516-43a7-acad-79a805ddaecf.png)
